apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-debug
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/pp0rtal/debug-argocd"
    targetRevision: HEAD
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: debug_argo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
