apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-debug-set
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pp0rtal/debug-argocd
        revision: HEAD
        files:
          - path: "*/config.json"
  template:
    metadata:
      name: "argo-debug-{{ .path.basename }}"
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: "https://github.com/pp0rtal/debug-argocd"
        targetRevision: HEAD
        path: "{{ .path.path }}/k8s"
      destination:
        server: https://kubernetes.default.svc
        namespace: debug-argo

      syncPolicy:
        syncOptions:
          - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true
  templatePatch: |
    metadata:
      annotations: {{ .annotations | toYaml | nindent 8 }}
