apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.github-ping-trello: |
    url: https://e7d3-78-120-131-110.ngrok-free.app
    headers:
    - name: "Content-Type"
      value: "application/json"

  template.sync-operation: |
    webhook:
      github-ping-trello:
        method: POST
        body: |
          {{ toJson .app }}

  trigger.sync-operation: |
    - when: app.status?.operationState?.phase in ['Succeeded']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
    - when: app.status?.operationState?.phase in ['Running']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
    - when: app.status?.operationState?.phase in ['Error', 'Failed']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
