apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.webhook.github-platform-ping-trello: |
    url: https://api.github.com/repos/360Learning/GitStats_Sandbox/dispatches
    headers:
    - name: "Content-Type"
      value: "application/json"
    - name: Authorization
      value: Bearer $github-platform-token

  template.sync-operation: |
    webhook:
      github-platform-ping-trello:
        method: POST
        body: |
          { "event_type": "ping_trello", "client_payload": {{ toJson .app.status.operationState }} }

  trigger.sync-operation: |
    - when: app.status?.operationState?.phase in ['Succeeded']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
    - when: app.status?.operationState?.phase in ['Running']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
    - when: app.status?.operationState?.phase in ['Error', 'Failed']
      oncePer: app.status?.operationState?.syncResult?.revision
      send: [sync-operation]
