apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: debug-argo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        command: ["/bin/sh", "-c"]
        args:
          - echo "App is running v9";
            sleep 99999999999;
            echo "backoff";
        ports:
        - containerPort: 80
